spring:
  datasource:
    url: ${MARIADB_URL_TEAM:jdbc:mariadb://localhost:3306/team}
    username: ${MARIADB_USER_TEAM:root}
    password: ${MARIADB_PASSWORD_TEAM:root}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MariaDBDialect

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}

  flyway:
    enabled: false

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

server:
  port: ${SERVER_PORT:0}