spring:
  datasource:
    url: ${MARIADB_URL_TEAM:jdbc:mariadb://localhost:3306/team}
    username: ${MARIADB_USER_TEAM:root}
    password: ${MARIADB_PASSWORD_TEAM:root}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: false
