spring:
  application:
    name: team-microservice

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  profiles:
    active: ${PROFILES:dev}

server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
