services:
  db_soccer:
    image: postgres:17
    container_name: db_soccer
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER_SOCCER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_SOCCER}
      POSTGRES_DB: ${POSTGRES_DB_SOCCER}
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  db_team:
    image: postgres:17
    container_name: db_team
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER_TEAM}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_TEAM}
      POSTGRES_DB: ${POSTGRES_DB_TEAM}
    ports:
      - "5433:5432"
    volumes:
      - postgresql_data_team:/var/lib/postgresql/data

  db_player:
    image: postgres:17
    container_name: db_player
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER_PLAYER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_PLAYER}
      POSTGRES_DB: ${POSTGRES_DB_PLAYER}
    ports:
      - "5434:5432"
    volumes:
      - postgresql_data_player:/var/lib/postgresql/data
  
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    container_name: api-gateway

  discovery-service:
    build: ./discovery-service
    ports:
      - "8761:8761"
    container_name: discovery-service

  rabbitmq:
    image: rabbitmq:4.0-management
    restart: always
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    container_name: rabbitmq

  soccer-microservice:
    build: ./soccer
    container_name: soccer-microservice
    environment:
      - POSTGRES_URL_SOCCER=${POSTGRES_URL_SOCCER}
      - POSTGRES_USER_SOCCER=${POSTGRES_USER_SOCCER}
      - POSTGRES_PASSWORD_SOCCER=${POSTGRES_PASSWORD_SOCCER}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - EUREKA_URL=${EUREKA_URL}
    depends_on:
      - db_soccer
      - discovery-service
      - api-gateway

  player-microservice:
    build: ./player
    container_name: player-microservice
    environment:
      - POSTGRES_URL_PLAYER=${POSTGRES_URL_PLAYER}
      - POSTGRES_USER_PLAYER=${POSTGRES_USER_PLAYER}
      - POSTGRES_PASSWORD_PLAYER=${POSTGRES_PASSWORD_PLAYER}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - EUREKA_URL=${EUREKA_URL}
    depends_on:
      - db_player
      - discovery-service
      - api-gateway
  
  team-microservice:
    build: ./team
    container_name: team-microservice
    environment:
      - POSTGRES_URL_TEAM=${POSTGRES_URL_TEAM}
      - POSTGRES_USER_TEAM=${POSTGRES_USER_TEAM}
      - POSTGRES_PASSWORD_TEAM=${POSTGRES_PASSWORD_TEAM}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - EUREKA_URL=${EUREKA_URL}
    depends_on:
      - db_team
      - discovery-service
      - api-gateway

volumes:
  postgresql_data:
    driver: local
  postgresql_data_team:
    driver: local
  postgresql_data_player:
    driver: local

