spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:soccer
    username: sa
    password: ''
    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  sql:
    init:
      mode: always  

server:
  port: 0