spring:
  datasource:
    url: ${MARIADB_URL_PLAYER}
    username: ${MARIADB_USER_PLAYER}
    password: ${MARIADB_PASSWORD_PLAYER}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  sql:
    init:
      mode: always
  
  application:
    name: player-microservice

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
