-- Tabla TEAM
CREATE TABLE team (
    team_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT,
    tenant_id   TEXT NOT NULL
);

-- Tabla PLAYER
CREATE TABLE player (
    player_id   BIGINT PRIMARY KEY,
    name        TEXT,
    team_id     BIGINT REFERENCES team(team_id),
    tenant_id   TEXT NOT NULL
);

-- Tabla GAME
CREATE TABLE game (
    game_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    local_goals     INT NOT NULL,
    visitor_goals   INT NOT NULL,
    finished        BOOLEAN NOT NULL,
    local_team_id   BIGINT REFERENCES team(team_id),
    visitor_team_id BIGINT REFERENCES team(team_id),
    tenant_id       TEXT NOT NULL
);

-- Activar RLS
ALTER TABLE team ENABLE ROW LEVEL SECURITY;
ALTER TABLE player ENABLE ROW LEVEL SECURITY;
ALTER TABLE game ENABLE ROW LEVEL SECURITY;

-- Política de aislamiento por tenant
CREATE POLICY team_rls ON team
    USING (tenant_id = current_setting('app.current_tenant'));

CREATE POLICY player_rls ON player
    USING (tenant_id = current_setting('app.current_tenant'));

CREATE POLICY game_rls ON game
    USING (tenant_id = current_setting('app.current_tenant'));
